# Generated by Django 3.2 on 2021-04-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('video', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('Yoga', 'Yoga'), ('Hiit', 'Hiit'), ('Cardio', 'Cardio'), ('Abs', 'Abs'), ('Weights', 'Weights'), ('Meditation', 'Meditation'), ('Streches', 'Streches')], default='Cardio', max_length=20)),
                ('duraration', models.CharField(max_length=20)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Pro', 'Pro')], default='Intermediate', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
