# Generated by Django 3.2 on 2021-04-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Video',
        ),
    ]
