# Generated by Django 3.2 on 2021-04-16 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0004_video_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked_video', to=settings.AUTH_USER_MODEL),
        ),
    ]
