# Generated by Django 3.2 on 2021-04-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.URLField(max_length=300),
        ),
    ]
