# Generated by Django 3.2 on 2021-04-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210415_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.JSONField(max_length=2500),
        ),
    ]
