# Generated by Django 3.2 on 2021-04-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text_five',
            field=models.TextField(default=1, max_length=8000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='text_four',
            field=models.TextField(default=1, max_length=8000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='text_three',
            field=models.TextField(default=1, max_length=8000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='text_two',
            field=models.TextField(default=1, max_length=8000),
            preserve_default=False,
        ),
    ]
