# Generated by Django 3.2 on 2021-04-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20210417_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text_six',
            field=models.TextField(default=1, max_length=8000),
            preserve_default=False,
        ),
    ]
