# Generated by Django 3.2 on 2021-04-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_text_six'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text_five',
            field=models.TextField(blank=True, max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_four',
            field=models.TextField(blank=True, max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_six',
            field=models.TextField(blank=True, max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_three',
            field=models.TextField(blank=True, max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_two',
            field=models.TextField(blank=True, max_length=8000, null=True),
        ),
    ]
