# Generated by Django 3.2 on 2021-04-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_rename_video_name_video_name'),
        ('recipes', '0005_recipe_like'),
        ('articles', '0010_auto_20210417_1424'),
        ('jwt_auth', '0004_auto_20210419_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='article',
            field=models.ManyToManyField(blank=True, related_name='saved_articles', to='articles.Article'),
        ),
        migrations.AddField(
            model_name='user',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='saved_recipes', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='user',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='saved_videos', to='videos.Video'),
        ),
    ]
