# Generated by Django 3.2 on 2021-04-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_ingredients'),
        ('videos', '0008_rename_video_name_video_name'),
        ('articles', '0011_article_category'),
        ('jwt_auth', '0005_auto_20210420_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='article',
            field=models.ManyToManyField(blank=True, related_name='articles', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='user',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='videos', to='videos.Video'),
        ),
    ]
