# Generated by Django 3.2 on 2021-04-21 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0006_auto_20210421_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='recipes',
            new_name='recipess',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='videos',
            new_name='videoss',
        ),
    ]
