# Generated by Django 3.2 on 2021-04-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_rename_video_name_video_name'),
        ('recipes', '0006_alter_recipe_ingredients'),
        ('jwt_auth', '0007_auto_20210421_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recipess',
            field=models.ManyToManyField(blank=True, related_name='recipess', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='videoss',
            field=models.ManyToManyField(blank=True, related_name='videoss', to='videos.Video'),
        ),
    ]
