# Generated by Django 3.2.1 on 2021-05-04 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0009_auto_20210421_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
    ]
