# Generated by Django 3.2 on 2021-04-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=1000)),
                ('image', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('High Protein', 'High Protein'), ('Low Carbs', 'Low Carbs'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Snacks', 'Snacks'), ('Dinner', 'Dinner'), ('Desserts', 'Desserts')], default='Vegan', max_length=50)),
                ('time', models.CharField(choices=[('Less than 20 mins', 'Less than 20 mins'), ('Less than 40 mins', 'Less than 40 mins'), ('Up to an hour', 'Up to an hour')], default='Less than 20 mins', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
