# Generated by Django 3.2 on 2021-04-16 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_alter_recipe_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked_recipe', to=settings.AUTH_USER_MODEL),
        ),
    ]
